### ISSUE TITLE
:)

### ISSUE THREAD

**Issue by ghost** [planetxort/Buffer-Overflow-Guide#2]
Hi, i do not have social media i read ur blog about oscp great great read, do you have an email where i can chat with you or a discord? If you do let me know and you can delete this comment so you can keep it private. Just have questions i know you will be able to answer :)

**Comment by redr0nin** [comment]
I am not currently open to providing hacking advice/guidance/mentorship at this time. Please refrain from creating GitHub issues on my projects in an attempt to ask me questions - thanks.
